version: '3.1'
services:
  es:
    image: my/es:1.0
    environment:
      - ES_JAVA_OPTS=-Xms128m -Xmx128m
    volumes:
      - ./data:/usr/share/elasticsearch/data
      - ./config/es2.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9201:9201
      - 9301:9301