version: '3.1'
services:
  es:
    image: elasticsearch:6.8.5
    environment:
      - ES_JAVA_OPTS=-Xms128m -Xmx128m
    volumes:
      - ./data:/usr/share/elasticsearch/data
      - ./config/es1.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
      - 9300:9300